id: TestIsEmailAddressInternal
version: -1
name: TestIsEmailAddressInternal
description: Test the IsEmailAddressInternal script that used to produce duplicates.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ca1500de-479a-4148-833c-224648249b0d
    type: start
    task:
      id: ca1500de-479a-4148-833c-224648249b0d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 245,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 7f111bdb-2e01-4485-87c1-9a230de0c8b8
    type: regular
    task:
      id: 7f111bdb-2e01-4485-87c1-9a230de0c8b8
      version: -1
      name: Set
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      append: {}
      key:
        simple: Account.Email.Address
      value:
        simple: anar@demisto.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 245,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: ddbe1cd1-3bcb-4bdc-8ff1-3c7dc9c5437e
    type: condition
    task:
      id: ddbe1cd1-3bcb-4bdc-8ff1-3c7dc9c5437e
      version: -1
      name: AreValuesEqual
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "7"
    scriptarguments:
      left:
        complex:
          root: Account
          accessor: Email.Address
          transformers:
          - operator: count
      right:
        simple: "1"
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 245,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 9d352601-8215-4312-8368-382bb17c5a6e
    type: title
    task:
      id: 9d352601-8215-4312-8368-382bb17c5a6e
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 2660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 31606802-117a-49b4-80ef-ed85c690614a
    type: regular
    task:
      id: 31606802-117a-49b4-80ef-ed85c690614a
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
      keysToKeep: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 245,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: efbe4b26-1e1c-493c-8879-87c4602c15ad
    type: regular
    task:
      id: efbe4b26-1e1c-493c-8879-87c4602c15ad
      version: -1
      name: IsEmailAddressInternal
      description: Checks if the email address is part of the internal domains
      scriptName: IsEmailAddressInternal
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      domain:
        simple: demisto.com
      email:
        simple: ${Account.Email.Address}
      include_subdomains: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 245,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: da332731-785a-457c-83f4-ff01f8e4c14a
    type: condition
    task:
      id: da332731-785a-457c-83f4-ff01f8e4c14a
      version: -1
      name: arevaluesequal internal
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "10"
      "yes":
      - "9"
    scriptarguments:
      left:
        complex:
          root: Account.Email.NetworkType
      right:
        simple: Internal
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 245,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 68a387f2-534c-4b20-8524-7117ec0f5fda
    type: regular
    task:
      id: 68a387f2-534c-4b20-8524-7117ec0f5fda
      version: -1
      name: IsEmailAddressInternal
      description: Checks if the email address is part of the internal domains
      scriptName: IsEmailAddressInternal
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      domain:
        simple: test.com
      email:
        simple: ${Account.Email.Address}
      include_subdomains: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 357.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: 5e1eb7ef-507f-4e2d-8141-d8b4607173d6
    type: regular
    task:
      id: 5e1eb7ef-507f-4e2d-8141-d8b4607173d6
      version: -1
      name: Error
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Failed Internal/External check
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: 0ca0a7b7-b89c-4368-8040-454b0dea786b
    type: condition
    task:
      id: 0ca0a7b7-b89c-4368-8040-454b0dea786b
      version: -1
      name: arevaluesequal external
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "10"
      "yes":
      - "14"
    scriptarguments:
      left:
        complex:
          root: Account.Email.NetworkType
      right:
        simple: External
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 357.5,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: 863f74df-3c57-4388-84dd-48108a32fcf1
    type: regular
    task:
      id: 863f74df-3c57-4388-84dd-48108a32fcf1
      version: -1
      name: IsEmailAddressInternal subdomain
      description: Checks if the email address is part of the internal domains
      scriptName: IsEmailAddressInternal
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      domain:
        simple: lol.com
      email:
        simple: example@lol_lol.lol.com
      include_subdomains:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: bacc8c9b-ace5-46f5-820b-d4e2072b41cb
    type: condition
    task:
      id: bacc8c9b-ace5-46f5-820b-d4e2072b41cb
      version: -1
      name: arevaluesequal internal
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "10"
      "yes":
      - "17"
    scriptarguments:
      left:
        complex:
          root: Account.Email.NetworkType
      right:
        simple: Internal
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: 47b4d5df-d9f3-4d9f-8d90-045623c00abd
    type: regular
    task:
      id: 47b4d5df-d9f3-4d9f-8d90-045623c00abd
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
      keysToKeep: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 470,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: edef27d3-f488-49e6-8d74-5ce295b6519b
    type: regular
    task:
      id: edef27d3-f488-49e6-8d74-5ce295b6519b
      version: -1
      name: IsEmailAddressesListInternal
      description: Checks if the email address is part of the internal domains
      scriptName: IsEmailAddressInternal
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      domain:
        simple: demisto.com
      email:
        simple: anar@demisto.com,example3@example.com
      include_subdomains: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 582.5,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: b96dfc5d-7dc1-4b0e-8b32-ed7f679544ec
    type: regular
    task:
      id: b96dfc5d-7dc1-4b0e-8b32-ed7f679544ec
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
      keysToKeep: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 582.5,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: 73fe7978-bcb8-4ba3-8f6f-c1942ae10dc0
    type: condition
    task:
      id: 73fe7978-bcb8-4ba3-8f6f-c1942ae10dc0
      version: -1
      name: ValidateVaules
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: AccountEmail
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: AccountEmail.Address
                      iscontext: true
                    right:
                      value:
                        simple: anar@demisto.com
                transformers:
                - operator: getField
                  args:
                    field:
                      value:
                        simple: NetworkType
            iscontext: true
          right:
            value:
              simple: Internal
      - - operator: isEqualString
          left:
            value:
              complex:
                root: AccountEmail
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: AccountEmail.Address
                      iscontext: true
                    right:
                      value:
                        simple: example3@example.com
                transformers:
                - operator: getField
                  args:
                    field:
                      value:
                        simple: NetworkType
            iscontext: true
          right:
            value:
              simple: External
    view: |-
      {
        "position": {
          "x": 582.5,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "20":
    id: "20"
    taskid: e80cb3ba-389d-4ee2-8b86-2374051e8c83
    type: regular
    task:
      id: e80cb3ba-389d-4ee2-8b86-2374051e8c83
      version: -1
      name: SetContext
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      append: {}
      key:
        simple: AccountEmail
      value:
        simple: ${Account.Email}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 582.5,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "4_7_yes": 0.74
    },
    "paper": {
      "dimensions": {
        "height": 2690,
        "width": 922.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
releaseNotes: "update script - check muliple email addresses"
