id: C2SEC-Domain Scan-Test
version: -1
name: C2SEC-Domain Scan-Test
description: |
  Launches a C2sec scan by domain name and waits for the scan to finish by polling its status in pre-defined intervals.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5a40ba4c-1384-4162-847a-4f7a02fa09c8
    type: start
    task:
      id: 5a40ba4c-1384-4162-847a-4f7a02fa09c8
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 827.5,
          "y": -70
        }
      }
    note: false
    timertriggers: []
  "14":
    id: "14"
    taskid: 80214125-ef23-4e14-8cc0-30f6510c73fc
    type: title
    task:
      id: 80214125-ef23-4e14-8cc0-30f6510c73fc
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 827.5,
          "y": 300
        }
      }
    note: false
    timertriggers: []
  "15":
    id: "15"
    taskid: e1af921f-809d-49d8-8cbd-f5b8f29cdb80
    type: playbook
    task:
      id: e1af921f-809d-49d8-8cbd-f5b8f29cdb80
      version: -1
      name: C2SEC-Domain Scan
      description: |
        Launches a C2sec scan by domain name and waits for the scan to finish by polling its status in pre-defined intervals.
      playbookName: C2SEC-Domain Scan
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      DomainName:
        simple: demisto.com
      interval:
        simple: "1"
      timeout:
        simple: "600"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 827.5,
          "y": 110
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 435,
        "width": 380,
        "x": 827.5,
        "y": -70
      }
    }
  }
inputs:
- key: DomainName
  value: {}
  required: true
  description: Domain Name
- key: interval
  value:
    simple: "1"
  required: false
  description: Polling frequency - how often the polling command should run (minutes)
- key: timeout
  value:
    simple: "600"
  required: false
  description: How much time to wait before a timeout occurs (minutes)
outputs: []