id: 998f0654-4a9b-4a53-8fb6-f25b88d587d6
version: 28
name: Confluence Integration Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e6ee841c-a188-4b7a-878e-f8df00f0c6fe
    type: start
    task:
      id: e6ee841c-a188-4b7a-878e-f8df00f0c6fe
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: c75c1453-2c37-4377-838b-309e3e6da4ca
    type: regular
    task:
      id: c75c1453-2c37-4377-838b-309e3e6da4ca
      version: -1
      name: Create new Confluence Space to add Page content
      script: Atlassian Confluence Server|||confluence-create-space
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      description:
        simple: Test Space from Playbook
      key:
        simple: PBSPC
      name:
        simple: Test Space from Playbook  - ${incident.id}:${incident.created}
      type:
        simple: global
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 515
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: 02d41e2a-9b32-44c8-8274-390876c9c431
    type: title
    task:
      id: 02d41e2a-9b32-44c8-8274-390876c9c431
      version: -1
      name: Create New Space
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
  "3":
    id: "3"
    taskid: 376ecf8b-e9a9-408e-80fb-ec521b5822b2
    type: regular
    task:
      id: 376ecf8b-e9a9-408e-80fb-ec521b5822b2
      version: -1
      name: Create new Confluence Page in PBSPC (Space created in previous step)
      script: Atlassian Confluence Server|||confluence-create-content
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      body:
        simple: <h1>Incident ID ${incident.id}</h1><p>Hello from Demisto Playbook,
          Incident ID ${incident.id} created on ${incident.created}.</p>
      space:
        simple: ${Confluence.Space.Key}
      title:
        simple: Test Page created from Playbook automation - ${incident.id}:${incident.created}
      type:
        simple: page
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1505
        }
      }
    note: false
    timertriggers: []
  "4":
    id: "4"
    taskid: f5eb9a45-958a-4ad3-89a9-6020bcbf86c8
    type: title
    task:
      id: f5eb9a45-958a-4ad3-89a9-6020bcbf86c8
      version: -1
      name: Create New Page
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1360
        }
      }
    note: false
    timertriggers: []
  "5":
    id: "5"
    taskid: ad2356c1-5789-4e26-87fe-b63c80bfe546
    type: regular
    task:
      id: ad2356c1-5789-4e26-87fe-b63c80bfe546
      version: -1
      name: Get a full List of Spaces from Confluence
      script: Atlassian Confluence Server|||confluence-list-spaces
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1010
        }
      }
    note: false
    timertriggers: []
  "6":
    id: "6"
    taskid: 7516c964-d1d0-4ad1-8684-ec1a7b466cd1
    type: title
    task:
      id: 7516c964-d1d0-4ad1-8684-ec1a7b466cd1
      version: -1
      name: List Spaces
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "28"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 690
        }
      }
    note: false
    timertriggers: []
  "7":
    id: "7"
    taskid: 061e8bba-b7fc-4dff-84ff-cf296c0df55d
    type: condition
    task:
      id: 061e8bba-b7fc-4dff-84ff-cf296c0df55d
      version: -1
      name: Check to see if any Spaces were returned and that the newly created Space
        exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Confluence.Space
            iscontext: true
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1185
        }
      }
    note: false
    timertriggers: []
  "8":
    id: "8"
    taskid: 631727b2-9cf9-4c28-8f85-addc8d21d39b
    type: regular
    task:
      id: 631727b2-9cf9-4c28-8f85-addc8d21d39b
      version: -1
      name: Manually check Space list and look for key PBSPC
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      value:
        simple: Something went wrong
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 4010
        }
      }
    note: false
    timertriggers: []
  "9":
    id: "9"
    taskid: fa9343c0-4b18-4ef3-8077-1753c58225c2
    type: condition
    task:
      id: fa9343c0-4b18-4ef3-8077-1753c58225c2
      version: -1
      name: Check to see if any Pages were returned and that the newly created Page
        exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Confluence.Content
            iscontext: true
    view: |-
      {
        "position": {
          "x": 695,
          "y": 2350
        }
      }
    note: false
    timertriggers: []
  "10":
    id: "10"
    taskid: 355df38e-c6b3-42f5-86ae-e5018609c76c
    type: title
    task:
      id: 355df38e-c6b3-42f5-86ae-e5018609c76c
      version: -1
      name: Update Page
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 2525
        }
      }
    note: false
    timertriggers: []
  "11":
    id: "11"
    taskid: 67f45404-536c-443e-847c-51e4e9eace27
    type: regular
    task:
      id: 67f45404-536c-443e-847c-51e4e9eace27
      version: -1
      name: Update Page body with success message
      script: Atlassian Confluence Server|||confluence-update-content
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      body:
        simple: ${Confluence.Content.body.storage.value}<br/><br/><p>This is a successful
          Page update!</p>
      currentversion:
        simple: ${Confluence.Content.Version}
      pageid:
        simple: ${Confluence.Content.ID}
      space: {}
      title:
        simple: ${Confluence.Content.Title}
      type:
        simple: page
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 2670
        }
      }
    note: false
    timertriggers: []
  "12":
    id: "12"
    taskid: ea72702c-66d2-451a-8e65-4a0c8715daa3
    type: regular
    task:
      id: ea72702c-66d2-451a-8e65-4a0c8715daa3
      version: -1
      name: Manually check Page list and look for newly created Page
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      value:
        simple: Something went wrong with new Page creation.
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 4010
        }
      }
    note: false
    timertriggers: []
  "13":
    id: "13"
    taskid: 70dfddcf-d304-4a96-85e3-d192b87c1210
    type: title
    task:
      id: 70dfddcf-d304-4a96-85e3-d192b87c1210
      version: -1
      name: Search for New Page
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "26"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1680
        }
      }
    note: false
    timertriggers: []
  "14":
    id: "14"
    taskid: d1001dc6-1be2-43a0-89a6-edd93e284923
    type: regular
    task:
      id: d1001dc6-1be2-43a0-89a6-edd93e284923
      version: -1
      name: Search for newly created Page using CQL
      script: Atlassian Confluence Server|||confluence-search-content
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      cql:
        simple: id = ${Confluence.Content.ID}
      cqlcontext: {}
      expand: {}
      limit: {}
      start: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 2175
        }
      }
    note: false
    timertriggers: []
  "16":
    id: "16"
    taskid: f6aa8926-1e79-4eec-8e9d-0fdc4583af0a
    type: regular
    task:
      id: f6aa8926-1e79-4eec-8e9d-0fdc4583af0a
      version: -1
      name: Close as failure
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: CustomCloseReason
      value:
        simple: SpaceCreationFailure
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 4185
        }
      }
    note: false
    timertriggers: []
  "17":
    id: "17"
    taskid: f10f25be-02f9-451f-8bac-df0efe3430d9
    type: regular
    task:
      id: f10f25be-02f9-451f-8bac-df0efe3430d9
      version: -1
      name: Close Incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason:
        simple: ${CustomCloseReason}
      id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 4360
        }
      }
    note: false
    timertriggers: []
  "18":
    id: "18"
    taskid: 1dec8160-c6fa-4989-8a3e-e8d6e63d9026
    type: title
    task:
      id: 1dec8160-c6fa-4989-8a3e-e8d6e63d9026
      version: -1
      name: Capture Page Image
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 2845
        }
      }
    note: false
    timertriggers: []
  "19":
    id: "19"
    taskid: 7fff6747-b0bd-4a53-8480-f92dd9baef5b
    type: regular
    task:
      id: 7fff6747-b0bd-4a53-8480-f92dd9baef5b
      version: -1
      name: Use raterize to capture page image
      script: Rasterize|||rasterize
      type: regular
      iscommand: true
      brand: Rasterize
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      height: {}
      type: {}
      url:
        complex:
          root: Confluence
          accessor: Content._links
          transformers:
          - operator: getField
            args:
              field:
                value:
                  simple: base
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: Confluence.Content._links.tinyui
                iscontext: true
      width: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 2990
        }
      }
    note: false
    timertriggers: []
  "20":
    id: "20"
    taskid: 9cdb9bc7-c89b-4c2c-87c9-825f6af9ece2
    type: regular
    task:
      id: 9cdb9bc7-c89b-4c2c-87c9-825f6af9ece2
      version: -1
      name: Review the page image in war room before deleting ...
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 3165
        }
      }
    note: false
    timertriggers: []
  "21":
    id: "21"
    taskid: 97c41fa8-b8c1-4148-8b63-2afca7191d76
    type: regular
    task:
      id: 97c41fa8-b8c1-4148-8b63-2afca7191d76
      version: -1
      name: Close as success
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: CustomCloseReason
      value:
        simple: PageCreationSuccess
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 920,
          "y": 4185
        }
      }
    note: false
    timertriggers: []
  "22":
    id: "22"
    taskid: 0a1b0c1e-863b-4477-87f4-233b299e4217
    type: title
    task:
      id: 0a1b0c1e-863b-4477-87f4-233b299e4217
      version: -1
      name: Delete Page
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "31"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 3340
        }
      }
    note: false
    timertriggers: []
  "23":
    id: "23"
    taskid: 55b9e7ed-2930-4d52-83a6-fe44b82799d1
    type: regular
    task:
      id: 55b9e7ed-2930-4d52-83a6-fe44b82799d1
      version: -1
      name: Get newly created page object from Confluence
      script: Atlassian Confluence Server|||confluence-get-content
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      key:
        simple: ${Confluence.Space.Key}
      title:
        simple: Test Page created from Playbook automation - ${incident.id}:${incident.created}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 3660
        }
      }
    note: false
    timertriggers: []
  "24":
    id: "24"
    taskid: cb7e4ef2-2085-4204-8522-45fd42c815be
    type: regular
    task:
      id: cb7e4ef2-2085-4204-8522-45fd42c815be
      version: -1
      name: Delete Confluence Page
      script: Atlassian Confluence Server|||confluence-delete-content
      type: regular
      iscommand: true
      brand: Atlassian Confluence Server
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      id:
        simple: ${Confluence.Content.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 3835
        }
      }
    note: false
    timertriggers: []
  "25":
    id: "25"
    taskid: 3f51b2c9-786d-400f-8e33-0cb0a795d7e4
    type: condition
    task:
      id: 3f51b2c9-786d-400f-8e33-0cb0a795d7e4
      version: -1
      name: Page Deletion successful?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "21"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsString
          left:
            value:
              simple: Confluence.Content.Result
            iscontext: true
          right:
            value:
              simple: success
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 910,
          "y": 4010
        }
      }
    note: false
    timertriggers: []
  "26":
    id: "26"
    taskid: 85892ba6-1329-4f2f-8659-4f660cc64486
    type: regular
    task:
      id: 85892ba6-1329-4f2f-8659-4f660cc64486
      version: -1
      name: Sleep for a few seconds...
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "30"
    scriptarguments:
      seconds:
        simple: "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1825
        }
      }
    note: false
    timertriggers: []
  "27":
    id: "27"
    taskid: 4c50c7b7-da55-45cd-8cfc-6f3d0a760995
    type: regular
    task:
      id: 4c50c7b7-da55-45cd-8cfc-6f3d0a760995
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
  "28":
    id: "28"
    taskid: 3b7278db-53ff-405c-8654-e46aa2ad7364
    type: regular
    task:
      id: 3b7278db-53ff-405c-8654-e46aa2ad7364
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 835
        }
      }
    note: false
    timertriggers: []
  "30":
    id: "30"
    taskid: 4c1f2f6b-e30d-4204-8fab-975a447fae77
    type: regular
    task:
      id: 4c1f2f6b-e30d-4204-8fab-975a447fae77
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 2000
        }
      }
    note: false
    timertriggers: []
  "31":
    id: "31"
    taskid: e47d976b-8151-46e0-8674-0a62a89cc5b9
    type: regular
    task:
      id: e47d976b-8151-46e0-8674-0a62a89cc5b9
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 3485
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {
      "7_8_#default#": 0.42
    },
    "paper": {
      "dimensions": {
        "height": 4405,
        "width": 1250,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
